force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADDR-{0000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Kanpur</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Lahore</fullName>
            </value>
            <value>
                <fullName>Tokyo</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Pathankot</fullName>
            </value>
            <value>
                <fullName>Karachi</fullName>
            </value>
            <value>
                <fullName>Peshawar</fullName>
            </value>
            <value>
                <fullName>Quetta</fullName>
            </value>
            <value>
                <fullName>Kyoto</fullName>
            </value>
            <value>
                <fullName>Osaka</fullName>
            </value>
            <value>
                <fullName>Sapporo</fullName>
            </value>
            <value>
                <fullName>Hiroshima</fullName>
            </value>
            <value>
                <fullName>Kawasaki</fullName>
            </value>
            <value>
                <fullName>Nagasaki</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Wuhan</fullName>
            </value>
            <value>
                <fullName>Anand</fullName>
            </value>
            <value>
                <fullName>Badoda</fullName>
            </value>
            <value>
                <fullName>Gandhinagar</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Howrah</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Madurai</fullName>
            </value>
            <value>
                <fullName>Harbin</fullName>
                <isActive>false</isActive>
                <label>Harbin</label>
            </value>
            <value>
                <fullName>Srilanka</fullName>
                <isActive>false</isActive>
                <label>Srilanka</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>Bharat</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
                <isActive>false</isActive>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>India</fullName>
                <isActive>false</isActive>
                <label>India</label>
            </value>
            <value>
                <fullName>Srilanka</fullName>
                <isActive>false</isActive>
                <label>Srilanka</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>Sindh</fullName>
            </value>
            <value>
                <fullName>Balochistan</fullName>
            </value>
            <value>
                <fullName>Azad Kashmir</fullName>
            </value>
            <value>
                <fullName>Hokkaido</fullName>
            </value>
            <value>
                <fullName>Chubu</fullName>
            </value>
            <value>
                <fullName>Ehime</fullName>
            </value>
            <value>
                <fullName>Kansal</fullName>
            </value>
            <value>
                <fullName>Provinces Of China</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Tamilnadu</fullName>
            </value>
            <value>
                <fullName>China State</fullName>
                <isActive>false</isActive>
                <label>China State</label>
            </value>
            <value>
                <fullName>Delhi</fullName>
                <isActive>false</isActive>
                <label>Delhi</label>
            </value>
            <value>
                <fullName>Japan State</fullName>
                <isActive>false</isActive>
                <label>Japan State</label>
            </value>
            <value>
                <fullName>Pakistan State</fullName>
                <isActive>false</isActive>
                <label>Pakistan State</label>
            </value>
            <value>
                <fullName>Telangana</fullName>
                <isActive>false</isActive>
                <label>Telangana</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APPLICATIONID-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AccountProvider.cls
public  with sharing class AccountProvider 
{
    @AuraEnabled
    public static List<Account> searchAccountRecord(Account  objAcc)
    {
       return [Select Id, Name, Rating, Type, CreatedDate, SLA__c from Account where Name =: objAcc.Name];
    }
   
    @AuraEnabled
    public static List<Contact> getRelatedContactRecords(Account objAccount)
    {
      return[Select Id, FirstName, LastName from Contact where Account.Name = : objAccount.Name];
    }
    @AuraEnabled
    public static List<Opportunity> getRelatedOpportunities(Account objAccount)
    {
      try 
      {
        return[Select Id, Name,StageName,CloseDate,AccountId from Opportunity where Account.Name = : objAccount.Name];  
      }
       catch (Exception e) 
       {
         return null;    
      }
    }
    @AuraEnabled
    public static List<Case> getRelatedCases(Account objAccount)
    {
      try 
      {
        return[Select Id,CaseNumber,Reason,Origin,Status from Case where Account.Name = : objAccount.Name];  
      }
       catch (Exception e) 
       {
         return null;    
      }
    }
    // @AuraEnabled
    // public static List<Address__c> getRelatedAddressRecords(String objAppName)
    // {
    //   System.debug('In Apex Server');
    //   System.debug('Applicant is:' +objAppName);
    //   return[Select Id , Country__c, State__c, City__c from Address__c where Applicant__r.Name = : objAppName];
    // }
    @AuraEnabled
    public static List<Account> searchAccountByChar(Account objAccount)
    {
      try
      {
        return [Select Name,Type,SLA__c,CreatedDate from Account where Name like :  objAccount.Name +'%'];
      }
     catch (Exception e) 
     {
        return null;
     }
   }
   
   @AuraEnabled(cacheable=true)
   public static List<Contact> getAccountDataUsingWire(Id accId)
   {
    try
    {
      return [Select Id, FirstName, LastName from Contact where Account.Id = : accId ];
    }
     catch (Exception e) 
    {
      return null;
    }
   }
   @AuraEnabled(cacheable=true)
   public static List<Account> getAllAccountsUsingWire()
   {
    try
    {
       return [select Id,Name,Rating,Type,CreatedDate from Account where CreatedDate < THIS_MONTH LIMIT 10];  
    } catch (Exception e)
     {
      return null;
    }
   }
   @AuraEnabled
   public static void deleteAccountRecord(Id accId )
   {
    try
    {
       Database.delete([select Id from Account where Id = : accId],false);  
    } catch (Exception e) {
      throw new AuraHandledException(e.getMessage());
    }
   }
   @AuraEnabled
   public static List<Account> getAllAccounts()
   {
      
    return NewDataProvider.getAllRecords();
   }
   @AuraEnabled
   public static List<Address__c> getRelatedAddressRecords(Applicant__c objApplicant)
   {
     Id appId = [select Id,First_Name__c,Last_Name__c from Applicant__c where First_Name__c =: objApplicant.First_Name__c and Last_Name__c =: objApplicant.Last_Name__c].Id;
     return [select Id,Country__c,State__c,City__c from Address__c where Applicant__c = : appId];
    }
    @AuraEnabled(cacheable=true)
    public static List<Account> getAccounts() {
    return [SELECT Id, Name, Industry, Phone FROM Account LIMIT 10];
  }
    @AuraEnabled
    public static String deleteSelectedAccounts(List<Id> accIds)
    {
     try{
      List<Account> accList = [select Id from Account where Id in : accIds];
      Database.delete(accList,false);
      return 'Records deleted Successfully';
     }
   catch(Exception e)
   {
    return 'Failed to delete Records';
   }
  }
   @AuraEnabled
   public static String getCustomMetadataRecords(String successCode)
   {
    try 
    {
      String msg  = [select Id,Success_Code__c,Message__c from Bank_Info__mdt where Success_Code__c = : successCode].Message__c;
      return msg;
    } catch (Exception e)
    {
      return null;
    }
   }
   @AuraEnabled
   public static Account getSingleAccount()
   {
    try {
      return [select Id,Name,AccountNumber,Industry from Account limit 1];
    } catch (Exception e) {
      return null;
    }
   }
   /*@AuraEnabled
   public static List<Case> getRelatedCasesForContact(String contactName)
   {
      return[select CaseNumber,Reason,Origin,Status from Case where Contact.Name=:contactName];
    }*/
    
   @AuraEnabled
    public static List<Opportunity> getOpportunities(Account objAcc)
    {
      return[SELECT Id, Name, Amount, CloseDate, Account.Name, Account.Rating 
FROM Opportunity WHERE Account.Name = : objAcc.Name AND Account.Rating = : objAcc.Rating];
    }
    @AuraEnabled
    public static List<Case> getRelatedCasesForContact(Contact objContact)
    {
      Id conId = [select Id from Contact where FirstName=:objContact.FirstName and LastName=:objContact.LastName limit 1].Id;
      return [select CaseNumber,Reason,Origin,Status from Case where ContactId=:conId];
    }
    @AuraEnabled
    public static List<Case> getRelatedCaseFrom(Case objCase)
    {
      return [select CaseNumber,Origin,Status,Priority from Case where CaseNumber = : objCase.CaseNumber];
    }
    @AuraEnabled
    public static List<Case> getRelatedCaseStatus(Case objCase, Integer pageSize,Integer pageNumber)
    {
      Integer offset = (pageNumber - 1) * pageSize;
      return [select CaseNumber,Origin,Status,Priority from Case where Status =: objCase.Status  LIMIT :pageSize OFFSET :offset]; 
    }
    @AuraEnabled
    public static Integer getCaseCount(Case objCase)
    {
      return [select COUNT() from Case where Status = : objCase.Status];
    }
  }
  
  
   
   
  