force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADDR-{0000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Kanpur</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Lahore</fullName>
            </value>
            <value>
                <fullName>Tokyo</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Pathankot</fullName>
            </value>
            <value>
                <fullName>Karachi</fullName>
            </value>
            <value>
                <fullName>Peshawar</fullName>
            </value>
            <value>
                <fullName>Quetta</fullName>
            </value>
            <value>
                <fullName>Kyoto</fullName>
            </value>
            <value>
                <fullName>Osaka</fullName>
            </value>
            <value>
                <fullName>Sapporo</fullName>
            </value>
            <value>
                <fullName>Hiroshima</fullName>
            </value>
            <value>
                <fullName>Kawasaki</fullName>
            </value>
            <value>
                <fullName>Nagasaki</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Wuhan</fullName>
            </value>
            <value>
                <fullName>Anand</fullName>
            </value>
            <value>
                <fullName>Badoda</fullName>
            </value>
            <value>
                <fullName>Gandhinagar</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Howrah</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Madurai</fullName>
            </value>
            <value>
                <fullName>Harbin</fullName>
                <isActive>false</isActive>
                <label>Harbin</label>
            </value>
            <value>
                <fullName>Srilanka</fullName>
                <isActive>false</isActive>
                <label>Srilanka</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>Sindh</fullName>
            </value>
            <value>
                <fullName>Balochistan</fullName>
            </value>
            <value>
                <fullName>Azad Kashmir</fullName>
            </value>
            <value>
                <fullName>Hokkaido</fullName>
            </value>
            <value>
                <fullName>Chubu</fullName>
            </value>
            <value>
                <fullName>Ehime</fullName>
            </value>
            <value>
                <fullName>Kansal</fullName>
            </value>
            <value>
                <fullName>Provinces Of China</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Tamilnadu</fullName>
            </value>
            <value>
                <fullName>China State</fullName>
                <isActive>false</isActive>
                <label>China State</label>
            </value>
            <value>
                <fullName>Delhi</fullName>
                <isActive>false</isActive>
                <label>Delhi</label>
            </value>
            <value>
                <fullName>Japan State</fullName>
                <isActive>false</isActive>
                <label>Japan State</label>
            </value>
            <value>
                <fullName>Pakistan State</fullName>
                <isActive>false</isActive>
                <label>Pakistan State</label>
            </value>
            <value>
                <fullName>Telangana</fullName>
                <isActive>false</isActive>
                <label>Telangana</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchAddressUpdate.cls
global class BatchAddressUpdate implements database.Batchable<sObject>
{
   global Database.QueryLocator start(Database.BatchableContext BC)
   {
     return Database.getQueryLocator('select Id, State__c, City__c,Applicant__r.Police_Verification__c from Address__c where Applicant__r.Police_Verification__c=false ');
   }
   global void execute(Database.BatchableContext BC, List<Address__c> adrList)
   {
     if(!adrList.isEmpty())
     {
       for(Address__c objAdr : adrList)
       {
         if(objAdr.State__c=='Maharashtra' && objAdr.City__c!='Pune')
             objAdr.City__c = 'Pune';
       }
       Database.update(adrList,false);
     }
   }
     global void finish(Database.BatchableContext BC)
     {
       System.debug('#Finish');
     }
  }