force-app/main/default/objects/Address__c/Address__c.object-meta.xml
<CustomObject>
    <label>Address</label>
    <nameField>
        <displayFormat>ADDR-{0000}</displayFormat>
        <label>Address ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Addresses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Address__c/fields/City__c.field-meta.xml
<CustomField>
    <fullName>City__c</fullName>
    <label>City</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>State__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nagpur</fullName>
            </value>
            <value>
                <fullName>Kanpur</fullName>
            </value>
            <value>
                <fullName>Pune</fullName>
            </value>
            <value>
                <fullName>Delhi</fullName>
            </value>
            <value>
                <fullName>Mumbai</fullName>
            </value>
            <value>
                <fullName>Lahore</fullName>
            </value>
            <value>
                <fullName>Tokyo</fullName>
            </value>
            <value>
                <fullName>Beijing</fullName>
            </value>
            <value>
                <fullName>Taiwan</fullName>
            </value>
            <value>
                <fullName>Pathankot</fullName>
            </value>
            <value>
                <fullName>Karachi</fullName>
            </value>
            <value>
                <fullName>Peshawar</fullName>
            </value>
            <value>
                <fullName>Quetta</fullName>
            </value>
            <value>
                <fullName>Kyoto</fullName>
            </value>
            <value>
                <fullName>Osaka</fullName>
            </value>
            <value>
                <fullName>Sapporo</fullName>
            </value>
            <value>
                <fullName>Hiroshima</fullName>
            </value>
            <value>
                <fullName>Kawasaki</fullName>
            </value>
            <value>
                <fullName>Nagasaki</fullName>
            </value>
            <value>
                <fullName>Shanghai</fullName>
            </value>
            <value>
                <fullName>Wuhan</fullName>
            </value>
            <value>
                <fullName>Anand</fullName>
            </value>
            <value>
                <fullName>Badoda</fullName>
            </value>
            <value>
                <fullName>Gandhinagar</fullName>
            </value>
            <value>
                <fullName>Kolkata</fullName>
            </value>
            <value>
                <fullName>Howrah</fullName>
            </value>
            <value>
                <fullName>Chennai</fullName>
            </value>
            <value>
                <fullName>Madurai</fullName>
            </value>
            <value>
                <fullName>Harbin</fullName>
                <isActive>false</isActive>
                <label>Harbin</label>
            </value>
            <value>
                <fullName>Srilanka</fullName>
                <isActive>false</isActive>
                <label>Srilanka</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <label>Country</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Japan</fullName>
            </value>
            <value>
                <fullName>China</fullName>
            </value>
            <value>
                <fullName>Pakistan</fullName>
            </value>
            <value>
                <fullName>Bharat</fullName>
            </value>
            <value>
                <fullName>Bangladesh</fullName>
                <isActive>false</isActive>
                <label>Bangladesh</label>
            </value>
            <value>
                <fullName>India</fullName>
                <isActive>false</isActive>
                <label>India</label>
            </value>
            <value>
                <fullName>Srilanka</fullName>
                <isActive>false</isActive>
                <label>Srilanka</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Address__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>State</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Country__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Maharashtra</fullName>
            </value>
            <value>
                <fullName>Uttar Pradesh</fullName>
            </value>
            <value>
                <fullName>Sindh</fullName>
            </value>
            <value>
                <fullName>Balochistan</fullName>
            </value>
            <value>
                <fullName>Azad Kashmir</fullName>
            </value>
            <value>
                <fullName>Hokkaido</fullName>
            </value>
            <value>
                <fullName>Chubu</fullName>
            </value>
            <value>
                <fullName>Ehime</fullName>
            </value>
            <value>
                <fullName>Kansal</fullName>
            </value>
            <value>
                <fullName>Provinces Of China</fullName>
            </value>
            <value>
                <fullName>Gujrat</fullName>
            </value>
            <value>
                <fullName>West Bengal</fullName>
            </value>
            <value>
                <fullName>Tamilnadu</fullName>
            </value>
            <value>
                <fullName>China State</fullName>
                <isActive>false</isActive>
                <label>China State</label>
            </value>
            <value>
                <fullName>Delhi</fullName>
                <isActive>false</isActive>
                <label>Delhi</label>
            </value>
            <value>
                <fullName>Japan State</fullName>
                <isActive>false</isActive>
                <label>Japan State</label>
            </value>
            <value>
                <fullName>Pakistan State</fullName>
                <isActive>false</isActive>
                <label>Pakistan State</label>
            </value>
            <value>
                <fullName>Telangana</fullName>
                <isActive>false</isActive>
                <label>Telangana</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APPLICATIONID-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Applicant__c/fields/Last_Name__c.field-meta.xml
<CustomField>
    <fullName>Last_Name__c</fullName>
    <label>Last Name</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/BatchApplicantToAddress.cls
public class BatchApplicantToAddress implements Database.Batchable<sObject>
{
   public Database.QueryLocator start(Database.BatchableContext BC)
   {
     String query = 'select Id, First_Name__c, Last_Name__c, Gender__c, Police_Verification__c from Applicant__c where Police_Verification__c = true';
     return Database.getQueryLocator(query);
   }
   public void execute(Database.BatchableContext BC, List<Applicant__c> appList)
   {
     Map<Id, Applicant__c> appMap = new Map<Id, Applicant__c>(appList);
     List<Address__c> adrList     = new List<Address__c>();
     for(Address__c objAdr : [select Id, Applicant__c, Country__c, State__c, City__c from Address__c where Applicant__c in : appMap.keySet()])
         adrList.add(objAdr);
     if(!adrList.isEmpty())
     {
       for(Address__c objAdr : adrList)
       {
         if(appMap.containsKey(objAdr.Applicant__c))
         {
           if(appMap.get(objAdr.Applicant__c).Gender__c == 'Male')
           {
             objAdr.Country__c = 'Bharat';
             objAdr.State__c   = 'Maharashtra';
             objAdr.City__c    =  'Pune';
           }
           else if(appMap.get(objAdr.Applicant__c).Gender__c == 'Female')
            {
             objAdr.Country__c = 'Bharat';
             objAdr.State__c   = 'Maharashtra';
             objAdr.City__c    = 'Nagpur';
           }
           else    
               objAdr.City__c    = ' ';
          }
        }
        Database.update(adrList, false);
     }
   }
   public void finish(Database.BatchableContext BC)
   {
     System.debug('#Finish');
   }
 }