force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>APPLICATIONID-{00000}</displayFormat>
        <label>Applicant ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Applicant__c/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gender</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Male</fullName>
            </value>
            <value>
                <fullName>Female</fullName>
            </value>
            <value>
                <fullName>Transgender</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/BatchChainingApplicantAccount.cls
global class BatchChainingApplicantAccount implements Database.Batchable<sObject>
{
   global Database.QueryLocator start(Database.BatchableContext BC)
   {
     return Database.getQueryLocator('select Id, Gender__c, Police_Verification__c from Applicant__c where Gender__c= \'Male\' and Police_Verification__c=false');
   }
   global void execute(Database.BatchableContext BC, List<Applicant__c> appList)
   {
    if(!appList.isEmpty())
    {
     for(Applicant__c objApp : appList)
         objApp.Police_Verification__c = true;
    }
    Database.update(appList, false);
   }
   global void finish(Database.BatchableContext BC)
   {
     Database.executeBatch(new BatchAccountRating(),100);
   }
}